name: Dirty But Classy
favicon: null
layout_spectrum: 1
typography_spectrum: 0.54401
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#baa999'
    - '#e9d2b2'
    - '#8b7f8b'
    - '#382a25'
    - '#ca7640'
  brandStrength: 0.8125
  lightness: 0.3465847058687359
  saturation: 0.16050430899485946
  rhythmicContrast: 0.7659287068527192
purpose: []
