name: Dirty But Classy
favicon: null
layout_spectrum: 1
typography_spectrum: 0.027300640009343624
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8404481236357242
  lightness: 0.3465847058687359
  saturation: 0.16050430899485946
  rhythmicContrast: 0.7659287068527192
purpose: []
